### PR TITLE
Get first test (#3) working

### PR DESCRIPTION
**Pull request by xy2iii**
Using tiji's last commits from December/January, simpler.

Get the test working. Once it works, setup a very simple testing infra that runs `cargo test` so we can know if it breaks.

- [x] Preprocessor
- [ ] Scheduler
- [ ] Add CI/automated testing (will probably just reuse Newton's stuff)

### CODE REVIEW

**Comment by xy2iii** [comment]
#3

**Comment by xy2iii** [comment]
Apologies for the messy history as this removes Newton's changes. The relevant changes are in `lib.rs` and `preprocessor.rs`.

**Comment by tijlleenders** [comment]
The struct after the preprocessor is as expected.

**Comment by xy2iii** [comment]
After review: we should just use what's already there on main. Will restart from there, should be quick to port over

**Pull request closed without merging**
