### PR TITLE
Added fmt script

### PR DESCRIPTION
**Pull request by sokorototo**

### CODE REVIEW

**Comment by tijlleenders** [comment]
@sokorototo Is this ready to be merged?

**Comment by tijlleenders** [comment]
@sokorototo What do you want to do with this PR? I'm converting it to draft if it's not ready for review.

**Comment by sokorototo** [comment]
Oh yeah, it's just some reformatting. You can just commit it since it does not touch any code.

**Review by tijlleenders — APPROVED** [review]

**Comment by sokorototo** [comment]
Nice

**Pull request merged**
