### PR TITLE
feat: Add repetition

### PR DESCRIPTION
**Pull request by xy2iii**

### CODE REVIEW

**Comment by xy2iii** [comment]
Task generator test:
```rust
Task::new(id, goal_id, duration_to_schedule)
Slot::new(task_id, start, end)
```
https://github.com/tijlleenders/ZinZen-scheduler/blob/repetition/src/task_generator.rs#L53-L82

Full tests:
https://github.com/tijlleenders/ZinZen-scheduler/blob/repetition/js-tests/repetition.ts#L4-L82

@tijlleenders

**Comment by xy2iii** [comment]
Switched from time to chrono since it did not support rounding. However chrono didn't support rounding for our time so I added it manually, making a PR to chrono after.

Relevant tests are in https://github.com/tijlleenders/ZinZen-scheduler/blob/repetition/src/task_generator.rs, the first 6 tests are unit tests, other are integration tests. (Should probably put the integration tests in tests/ later on.)

Js tests: https://github.com/tijlleenders/ZinZen-scheduler/blob/repetition/js-tests/repetition.ts

**Comment by sokorototo** [comment]
Ok so let me resolve the merge conflicts first

**Review by sokorototo — APPROVED** [review]

**Comment by xy2iii** [comment]
#25

**Pull request merged**
