### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by thinkrapido**

### CODE REVIEW

**Comment by thinkrapido** [comment]
Please review, if it's done

**Comment by tijlleenders** [comment]
@thinkrapido I have some minor tweaks to the docs - but I'm not allowed to push to this branch.  
I've published the additions on https://github.com/tijlleenders/ZinZen-scheduler/pull/444 and asked for your review. If OK you can merge.

**Review by thinkrapido — COMMENTED** [review]
ok

**Review by thinkrapido — COMMENTED** [review]
ok

**Review by thinkrapido — COMMENTED** [review]
ok

**Review by tijlleenders — APPROVED** [review]
Thanks!

**Pull request merged**
