### PR TITLE
feat: mixing daily and weekly budgets

### PR DESCRIPTION
**Pull request by moaz-mokhtar**
Resolves https://github.com/tijlleenders/ZinZen-scheduler/issues/287

---

**Plan**
- [x] Basic code refactor done by https://github.com/tijlleenders/ZinZen-scheduler/pull/292 
- [x] Create `json` test cases
- [x] Initial function design
- [x] Design discussion
- [ ] Develop feature
- [x] Test feature 

---

Input expected to be as below example:
```json
{
    "startDate": "2022-10-01T00:00:00",
    "endDate": "2022-11-01T00:00:00",
    "goals": {
        "1": {
            "id": "1",
            "title": "work",
            "budgets": [
                {
                    "budget_type": "Weekly",
                    "min": 35,
                    "max": 40
                },
                {
                    "budget_type": "Daily",
                    "min": 5,
                    "max": 10
                }
            ]
        }
    }
}
```

### CODE REVIEW

**Review by tijlleenders — APPROVED** [review]
Cool!

Can you add a new PR with a test that tests the min duration? The min duration is post-task_placer code which is not hit with the current test case.

**Comment by moaz-mokhtar** [comment]
> Cool!
> 
> Can you add a new PR with a test that tests the min duration? The min duration is post-task_placer code which is not hit with the current test case.

Seeking more clarification about this

**Comment by tijlleenders** [comment]
You're right, that is not clear.
In fact, now that I read it back I can't even figure out what I meant... Sorry about that!

If I find a failing test case I will add that to the repo as a complete input/ouput.json pair.

**Comment by moaz-mokhtar** [comment]
No worries at all

**Pull request merged**
