### PR TITLE
test: fix failed test cases

### PR DESCRIPTION
**Pull request by moaz-mokhtar**
Resolves https://github.com/tijlleenders/ZinZen-scheduler/issues/315

--- 
### Initial
- [x] Developed test feature to printout actual output into `actual_output.json` file. Related to issue https://github.com/tijlleenders/ZinZen-scheduler/issues/306 as per comment https://github.com/tijlleenders/ZinZen-scheduler/issues/306#issuecomment-1557878400
- [x] Debug test case `bug_215`
- [x] Fixed test case `bug_215`
- [ ] <del> Fix test case `flex_repeat_2`
- [ ] <del> Fix test case `flex_repeat_3`

### Function `calculate_flexibility`
- [x] Isolate function `calculate_flexibility` 
- [x] Developed basic unit tests
- [ ] <del> Force respect `Task.duration` to be the minimum for each task
- [ ] <del> Fix passing to the function `calculate_flexibility` tasks/Steps with status which is not `ReadyToSchedule`

### Function `find_best_slots`
- [x] Isolate function `find_best_slots` 
- [ ] <del> Developed basic unit tests
- Refactor functionality for getting conflicts for slots as below:
    - [x] Developed function `Slot::get_conflicts_in_slots` with basic tests cases
    - [x] Developed function `Slot::get_conflicts_in_tasks` with basic tests cases
    - [x] Developed function `Task::get_conflicts_in_tasks` with basic test cases
    - [x] Developed function `Slot::generate_schedulable_slots` with basic test cases
    - [x] Using `Task::get_conflicts_in_tasks` in function `find_best_slots`

### Sub PR
- [x] Resolved `filter_timing` issue as mentioned in below Issues section. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/319 
- [x] Resolve issue in `Task::remove_slot` which it is not removing slots properly. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/320 
    - [x] Resolved issue in `Sub` impl for `Slot`. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/322
    - Renamed Function `Task::remove_slot` into `Task::remove_conflicted_slots`
- [x] Implement a custom `Debug` and `Display` traits for `Slot` struct. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/323
- [x] Fixed flexibility calculation for `bug_215`. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/324 
- [x] Remove flex repeat tests for now. Check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/325 
  - [**UPDATE 2023-06-19**: Tests `flex_repeat_2` and `flex_repeat_3` deleted. Check issue https://github.com/tijlleenders/ZinZen-scheduler/issues/326 and sub-PR]
---
## Issues
- Flexibility calculation is not accurate as below:
  - For task: "water the plants indoors", correct flexibility is 14 but it is calculated as 34.
    - Also that leads that it added slots out of budget. It has been noticed inside function `schedule`, after calling function `tasks_to_place.sort_on_flexibility()` and before calling function `find_best_slots`
  - For task: "sleep", correct flexibility is 19 but it is calculated as 22.
  - NOTE: Resolved by sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/324 
- Filter timing need to be enhanced as below:
  - Task title "sleep" after `filter_timing`, it contains extra hours out of deadline which leads to wrong scheduling. 
  - NOTE: Issue resolved, check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/319 
        Input is like below:
        ```
        {
            "startDate": "2023-01-03T00:00:00",
            "endDate": "2023-01-10T00:00:00",
            "goals": {
                "1": {
                    "id": "1",
                    "title": "sleep",
                    "min_duration": 8,
                    "filters": {
                        "after_time": 22,
                        "before_time": 8
                    }
                },
                ---
                ---
                ---
            }
        }
        ```

        Task as below:
        ```
        Task
            title: sleep 
            slots:
                2023-01-03 00 - 2023-01-03 08
                2023-01-03 22 - 2023-01-04 08
                2023-01-04 22 - 2023-01-05 08
                2023-01-05 22 - 2023-01-06 08
                2023-01-06 22 - 2023-01-07 08
                2023-01-07 22 - 2023-01-08 08
                2023-01-09 22 - 2023-01-10 08 (here the issue)
        ```
- Found issue while resolving https://github.com/tijlleenders/ZinZen-scheduler/pull/319 in `Task::remove_slot` which it is not removing slots properly as below sample:
  - NOTE: this issue resolved, check sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/320

    ```
    // "chosen_slot" to be removed from all tasks:
    Slot: 2023-01-03 00 to 08 (8 hours)

    // "Task.slot" which has less duration than chosen_slot but not removed
    Task.slot: 2023-01-03 01 to 03 (2 hour)

    // Current design doesn't remove intersected timing but subtract difference, which causing wrong scheduling as below result.
    Task.Slot1: 2023-01-03 00 to 01 (1 hour) [<< that causing wrong scheduling]
    Task.Slot2: 2023-01-03 03 to 08 (5 hour) [<< giving more time to the task which out of budget]

    // Correct respond should be as below:
    Task.Slot 2023-01-03 00 to 03 [REMOVED, so task shouldn't have this] 
    ```

### CODE REVIEW

**Comment by tijlleenders** [comment]
@moaz-mokhtar Great!  
Can you also move it outside of build.rs to a separate /bin that can be called independently of build script?

**Comment by moaz-mokhtar** [comment]
Thanks,
Ok

**Comment by moaz-mokhtar** [comment]
@tijlleenders Kindly can you confirm the accuracy of current `actual_output.json` for the 3 tests `bug_215`, `flex_duration_2`, and `flex_duration_3`?

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
`bug-215` - This is a weird test case - but I can manually find the expectation - and the current expectation `output.json` and `actual_output.json` are both wrong.  
Let's discuss.

**Comment by moaz-mokhtar** [comment]
> @moaz-mokhtar Great! Can you also move it outside of build.rs to a separate /bin that can be called independently of build script?

Can I continue this by a separate PR related the issue https://github.com/tijlleenders/ZinZen-scheduler/issues/306?

**Comment by moaz-mokhtar** [comment]
As discussed with @tijlleenders , for `bug_215` found that final result should be as below:

image

**Comment by tijlleenders** [comment]
@moaz-mokhtar 
00bf1c739e26ed8d86340e5591c63334bfceb72f  

Calculating flexibility will only happen for Steps that are ready to be scheduled. So it doesn't make sense to have tests for other Step statusses - or you should tet that that would panic.

**Comment by moaz-mokhtar** [comment]
> 



> @moaz-mokhtar [00bf1c7](https://github.com/tijlleenders/ZinZen-scheduler/commit/00bf1c739e26ed8d86340e5591c63334bfceb72f)
> 
> Calculating flexibility will only happen for Steps that are ready to be scheduled. So it doesn't make sense to have tests for other Step statusses - or you should tet that that would panic.

Ok, so I fix it, so any other status than `ReadyToSchedule`, will be panic

**Comment by moaz-mokhtar** [comment]
I did fix this to avoid any type of TaskStatus::ReadyToSchedule, but all tasks failed. Check commit https://github.com/tijlleenders/ZinZen-scheduler/pull/317/commits/33cb54d24af8c02136f18e407a04c517d7fcd159 

This is the code to prevent any task which not ReadyToSchedule:
```
if self.status != TaskStatus::ReadyToSchedule {
            panic!(
                "TaskStatus must be ReadyToSchedule, but it is now TaskStatus::{:?}",
                self.status
            );
        }
```

So I did generate a log after run `cargo test --release` and found it panicked 78 times as below samples:
```shell
thread 'issue_284_filter_days_of_week_1day' panicked at 'TaskStatus must be ReadyToSchedule, but it is now TaskStatus::Scheduled', src/services/flexibility.rs:7:13

...

thread 'issue_276_weekdays_filter_on_budget' panicked at 'TaskStatus must be ReadyToSchedule, but it is now TaskStatus::BudgetMinWaitingForAdjustment', src/services/flexibility.rs:7:13

---

thread 'i312' panicked at 'TaskStatus must be ReadyToSchedule, but it is now TaskStatus::Impossible', src/services/flexibility.rs:7:13

---
---

```

**Comment by moaz-mokhtar** [comment]
Another note which related to function `calculate_flexibility`, check commit https://github.com/tijlleenders/ZinZen-scheduler/pull/317/commits/06a75130a36c73774bb1a5e3cb56888eeba0c10d 
I think we need take in consideration when calculating flexibility:
- field `duration` is not the same on all tasks, somtimes it is for BudgetTask.min or for Goal.min_duration. That is why some goals with Budget.min, will not be considered.
- Task with status, : `TaskStatus::BudgetMinWaitingForAdjustment` have duration of BudgetTask.min, so need to split it based on `min_duration` if available
- New rule as below code snippet will be applied for tasks which Task.duration is the Goal.min_duration.
```rust
pub fn calculate_flexibility(&mut self) {
        ---
        let flexibility = self.slots.iter().fold(0, |acc, slot| {
            ---
            if slot_duration >= task_duration {
                acc + slot_duration - task_duration + 1
            } else {
                acc
            }
        });

        ---
    }
```
So what do you think? @tijlleenders

**Comment by tijlleenders** [comment]
> So I did generate a log after run `cargo test --release` and found it panicked 78 times  

That was expected.  
Next step is to let the sort function only sort what is ready to schedule - and change the status to ready to schedule for the other Steps whenever appropriate.

**Comment by tijlleenders** [comment]
@moaz-mokhtar 

>TaskStatus::BudgetMinWaitingForAdjustment have duration of BudgetTask.min, so need to split it based on min_duration if available

Sounds reasonable. Just keep in mind there could be a 'leftover' number of hours that is not cleanly divisible by the min_duration.

**Comment by moaz-mokhtar** [comment]
> 



> @moaz-mokhtar
> 
> > TaskStatus::BudgetMinWaitingForAdjustment have duration of BudgetTask.min, so need to split it based on min_duration if available
> 
> Sounds reasonable. Just keep in mind there could be a 'leftover' number of hours that is not cleanly divisible by the min_duration.

But in case `min_duration` is not available, that is tricky!

**Comment by tijlleenders** [comment]
> But in case `min_duration` is not available, that is tricky!  

Then I think it's safe to assume 1h - at least for now.

**Comment by moaz-mokhtar** [comment]
As agreed in Meeting 2023-06-01, to focus more on make those 3 test cases passed and give low priority to refactoring, so I did return back below changes:
- Avoid filtering tasks which not `TaskStatus::ReadyToSchedule`, I can propose to create an issue for this to be handled in a separated PR.
- Avoid new function `generate_tasks_by_budget` and just keep it as it was
---

Now returned to only 3 failed test cases and I found below:
- For test case `flex_repeat_2`, found the `actual_output.json` have little difference in the lastest sleep slot.
  
  ```json
  // ============
  // ouptut.json
  {
      "taskid": 154,
      "goalid": "2",
      "title": "sleep",
      "duration": 10,
      "start": "2022-10-31T22:00:00",
      "deadline": "2022-11-01T08:00:00"
  }
  
  // =============
  // actual_output.json
  {
      "taskid": 154,
      "goalid": "2",
      "title": "sleep",
      "duration": 2,
      "start": "2022-10-31T22:00:00",
      "deadline": "2022-11-01T00:00:00"
  }
  ```
  
- For test case `flex_repeat_3`, found no difference but just extra `sleep` slot in the `impossible` section as below
  
  ```json
  // ============
  // ouptut.json
  
  
  // =============
  // actual_output.json
  {
      "taskid": 48,
      "goalid": "2",
      "title": "sleep",
      "duration": 2,
      "start": "2022-10-01T08:00:00",
      "deadline": "2022-10-15T00:00:00"
  }
  ```
- For test case `bug_215`, I'm still debugging but currently I found that `sleep` slots passed to the function `output_formatter` have an inappropriate slot timing. So expected that issue (make `sleep` slots inappropriate) happening in previous function `find_best_slots`

**Comment by tijlleenders** [comment]
@moaz-mokhtar What is the reason behind 'schedulable slots'? The number of possible positions is easily calculable based on the slot size and the min_duration. This seems to add complexity as now the same hour will 'exist' in multiple schedulable slots.

**Comment by moaz-mokhtar** [comment]
> @moaz-mokhtar What is the reason behind 'schedulable slots'? The number of possible positions is easily calculable based on the slot size and the min_duration. This seems to add complexity as now the same hour will 'exist' in multiple schedulable slots.

The reason behind `generate_schedulable_slots`, is wrong scheduling. 
- Splitting slots into 1 hour slots, leads to calculate flexibility for each splitted slot separately which leads to wrong scheduling and leads to schedule the same task many times in a day.
- That is appeared in case `bug_215`, the `actual_output` shows that sleep splitted in the same day into many slots like sleep @1am for 1 hour then @3am for 1 or 2 hours, etc.

Also it is easy to change this, it one line of code, so you test it by yourself.
```rust
// Using `generate_schedulable_slots`
fn get_conflicts_in_tasks(&self, slots_list: &[Task]) -> Vec<SlotConflict> {
        ---
        ---
        ---
        self.slots.iter().for_each(|slot| {
            let schedulable_slots = slot.generate_schedulable_slots(self.duration);
            ---
        });
        ---
        ---
    }

// =============================
// Using `divide_into_1h_slots`
fn get_conflicts_in_tasks(&self, slots_list: &[Task]) -> Vec<SlotConflict> {
        ---
        ---
        ---
        self.slots.iter().for_each(|slot| {
            let schedulable_slots = slot.divide_into_1h_slots();
            ---
        });
        ---
        ---
    }


```

**Comment by tijlleenders** [comment]
@moaz-mokhtar So it is used primarily for calculating conflicts in a more readable way? Sounds good!

**Comment by moaz-mokhtar** [comment]
After fixing some issues in sub-PR specially sub-PR https://github.com/tijlleenders/ZinZen-scheduler/pull/320, found below:
- test case `bug_215` passed and provide accurate scheduling, but still issue in `calculate_flexibility` specially for tasks like `sleep` which overlap to next day.
- found 30 failed cases and found other issues as illustrated in the failed issues.
- Some `output.json` and `actual_output.json` are not the accurate result

---

## 30 Failed cases

### Reasons for more failed cases
- Many cases failed because default behavior for splitting changed; if task have a `min_duration`, it will not be splitted in scheduling in the same day. That caused another issue as next 2 points
- Sleep task flexibility calculation went wrong, because of last slot calculation when condition `slot_duration < task_duration` happen 
- Also in that condition, tasks with big `min_duration` which not for a daily task ex: budget tasks, children tasks, tasks with duration for week or month duration; that tasks are not understood in the function `calculate_flexibility`. That is why a lot of failed cases because of `panicked at index out of bounds`

Check latest 2 commits https://github.com/tijlleenders/ZinZen-scheduler/pull/317/commits/a308da87dc418a1ec913f299dddcd07f160c8fc1 and https://github.com/tijlleenders/ZinZen-scheduler/pull/317/commits/a4de2ec3bd95d36ad8b001e29d17a26c3d35168f

### List of 30 failed cases

- `budget_with_no_children`: panicked at `index out of bounds`
  
- `bug_236`: panicked at `index out of bounds`
  
- `children_with_over_duration`: panicked at `index out of bounds`
  
- `demo_1_old`: panicked at `index out of bounds`
  
- `demo_2_with_filler_with_budget`: panicked at `index out of bounds`
  
- `different_repetition_goals`: found `actual_output` is valid because unsplitable goal `work`
  
- `every_6_hours`: panicked at `index out of bounds`
  
- `every_6_hours_2`: panicked at `index out of bounds`
  
- `flex_duration_2`: panicked at `index out of bounds`
  
- `flex_repeat_2`: panicked at `index out of bounds`
  
- `flex_repeat_3`: panicked at `index out of bounds`
  
- `goals_dependency`:
  
  - both `output.json` and `actual_output.json` are wrong
    
  - Issue is that dependencies not scheduled propely
    
- `goals_hierarchy`: panicked at `index out of bounds`
  
- `i293_postpone_2`: Corrected `output.json` to match `actual_output.json`
  
- `i309`: panicked at `index out of bounds`
  
- `impossible_2`: found `actual_output` is valid because unsplitable goal `work`
  
- `issue_276_weekdays_filter_on_budget`: panicked at `index out of bounds`
  
- `issue_284_filter_days_of_week_with_impossible`: panicked at `index out of bounds`
  
- `issue_284_no_repeat_large_dur_and_timespan`: panicked at `index out of bounds`
  
- `issue_284_no_repeat_large_dur_with_impossible`: panicked at `index out of bounds`
  
- `planned_goals_hierarchy`: panicked at `index out of bounds`
  
- `realistic_weekend_repetition_1`:
  
  - `actual_output` make sense which unsplittabled tasks
    
  - both `output` and `actual_output` have issue which first 2 days (2022-09-01 and 02) have tasks although they are not `weekends` (which means issue on start of the scheduling)
    
- `show_sleep`: panicked at `index out of bounds`
  
- `sleep_1`: panicked at `index out of bounds`
  
- `slot-reduced-1`: found `actual_output` is valid from a point of view
  
- `split-1`: found `actual_output` is valid because unsplitable goal `work`
  
- `split-2`: found `actual_output` is valid because unsplitable goal `work`
  
- `split-3`: found `actual_output` is valid because unsplitable goal `work`
  
- `split-4`: found `actual_output` is valid because unsplitable goal `work`
  
- `x_per_day_4`:
  
  - In goal `play chess`, what is meaning of `"repeat": "3/day"`? Can we use it to split tasks in a day instead of adding more fields?
    
  - Found misunderstand here, should `repeat` 3 times per day or 3 days? check below code and debug log:
    
    - code snippet:
      
    
    ```rust
    match repeat {
            Repetition::DAILY(_) => {
                dbg!(result);
                result = result
                    .checked_add_days(Days::new(1))
                    .unwrap()
                    .with_hour(0)
                    .unwrap()
                    .with_minute(0)
                    .unwrap()
                    .with_second(0)
                    .unwrap();
                dbg!(result);
                result
    }
    ```
    
    - Debug Log:
      
    
    ````bash
    ```bash
    [src/models/goal/impls.rs:113] &time_slots_iterator = TimeSlotsIterator {
        timeline: Timeline {
            slots: {
                Slot { 
                    start:   2022-11-11 07,
                     end:    2022-11-12 00, 
                },
            },
        },
        repetition: Some(
            DAILY(
                3,
            ),
        ),
        filters: Some(
            TimeFilter {
                after_time: Some(
                    7,
                ),
                before_time: None,
                on_days: None,
                not_on: None,
            },
        ),
        current_start_position: 2022-11-11T07:00:00,
    }
    [src/models/slots_iterator/utils.rs:15] result = 2022-11-11T07:00:00
    [src/models/slots_iterator/utils.rs:25] result = 2022-11-12T00:00:00
    ````

**Review by tijlleenders — APPROVED** [review]

**Pull request merged**
