### PR TITLE
Implement weekly repetitions

### LINKED ISSUE #107: Implement repetition "weekly"
To allow someone to specify something to be done once a week without specifying which day of the week. e.g. "study french duration 2hrs once a week". Also should be able to handle time bounds e.g. "study french duration 2hrs once a week, but between 6pm and 10pm"

### PR DESCRIPTION
**Pull request by egithinji**
Related to #107.
This handles weekly repetitions but without aftertime/beforetime bounds.

### CODE REVIEW

**Review by JacobJax — DISMISSED** [review]
closes #117

**Review by tijlleenders — CHANGES_REQUESTED** [review]
@JacobJax Please include the deno test in #115 to complete this.
The test should've been made first.

**Comment by egithinji** [comment]
I think this can now be merged since it now includes integration tests for 'weekly' that are passing.
However it doesn't close #117 because we need to add test for weekly with time-bounds.

**Review by tijlleenders — APPROVED** [review]
Nice!

**Pull request merged**
