### PR TITLE
test: replaced repeat values in input.json files as requested

### PR DESCRIPTION
**Pull request by moaz-mokhtar**
Resolves https://github.com/tijlleenders/ZinZen-scheduler/issues/347

---

Replaced repeat values in input.json files like `Weekends`, `Weekdays` and used instead field `filter.on_days`

### CODE REVIEW

**Review by tijlleenders — CHANGES_REQUESTED** [review]
On second thought, a weekly repetition would fit better whenever 'Weekdays' or 'Weekends' is used, right?

**Comment by moaz-mokhtar** [comment]
> On second thought, a weekly repetition would fit better whenever 'Weekdays' or 'Weekends' is used, right?

I'm not sure about system behavior. 
- If we said `daily`, it will filter `on_days` from all other week days. 
- If we said `weekly`, i'm not sure about behavior

**Comment by tijlleenders** [comment]
It is simple.  
If I say 'Run 5km weekends' do you expect to run 5km or 10km?  
A daily repeat on a timeline filtered for Sat + Sun would result in 2 steps (2x5km) - a weekly repeat would result in 1 step (1x 5km with a timeline of Sat + Sun).

**Comment by moaz-mokhtar** [comment]
I did run `cargo test` and found differences. Check commit: https://github.com/tijlleenders/ZinZen-scheduler/pull/353/commits/91c2997932f4bbb28f30822958523010bbba1184

**Comment by moaz-mokhtar** [comment]
> 



> It is simple. If I say 'Run 5km weekends' do you expect to run 5km or 10km? A daily repeat on a timeline filtered for Sat + Sun would result in 2 steps (2x5km) - a weekly repeat would result in 1 step (1x 5km with a timeline of Sat + Sun).

Thanks, I'm going to change

**Comment by moaz-mokhtar** [comment]
I found many many cases that contains `on_days` with `daily`, so should I change all of them or just who changed in this a prev commit?

**Comment by moaz-mokhtar** [comment]
> I found many many cases that contains `on_days` with `daily`, so should I change all of them or just who changed in this a prev commit?

As expected, system behavior is not as logical as it should be. Below is an example until I test all affected cases:
- For test case `before_7`, it should schedule a task `run` on Sats and Suns for a month timeline. So:
   - when set `"repeat": "weekly"`, it schedule it on a single day only which `Sat`.
      -  I did test swap `on_days` and the same result only `Sat`s.
   - when set  `"repeat": "daily"`, it schedule it correctly of `Sat`s and `Sun`s

**Comment by moaz-mokhtar** [comment]
> > I found many many cases that contains `on_days` with `daily`, so should I change all of them or just who changed in this a prev commit?
> 
> As expected, system behavior is not as logical as it should be. Below is an example until I test all affected cases:
> 
>     * For test case `before_7`, it should schedule a task `run` on Sats and Suns for a month timeline. So:
>       
>       * when set `"repeat": "weekly"`, it schedule it on a single day only which `Sat`.
>         
>         * I did test swap `on_days` and the same result only `Sat`s.
>       * when set  `"repeat": "daily"`, it schedule it correctly of `Sat`s and `Sun`s

The same concern for the other 3 cases as per commits: https://github.com/tijlleenders/ZinZen-scheduler/pull/353/commits/7c51c6edbf0a866ab5d79b53a6ae4223a383ada2 and https://github.com/tijlleenders/ZinZen-scheduler/pull/353/commits/d4451c424884aa83bcb8168cbb383dcdeb2f8e39

**Review by tijlleenders — APPROVED** [review]
Nice - on to the next test case!

**Pull request merged**
