### PR TITLE
Documentation test generation feature flag

### PR DESCRIPTION
**Pull request by kobe-reygel**
- documented the recently created need for using the generate-tests feature flag
- introduced the concept of ADRs (Architectural Decision Records)

### CODE REVIEW

**Comment by tijlleenders** [comment]
@kobe-reygel 
This is a great idea!  

About the feature:  
Wouldn't it be better to have the feature on by default and only disable it manually when doing a ```cargo publish```?  
This way new people on the project will not run into trouble, and the few times we do need to publish and forget the flag we'll get the error message reminding us about the flag required to publish.

**Comment by kobe-reygel** [comment]
Yes that would be an option. I don't have a strong opinion either way, so I'll leave that up to you what you find most convenient :)

Only small counter-argument that I could imagine is that there really is no need to do the work of analysing the JSONS directory every build. Only when we add tests (or delete them). This notion is the reason I opted for the current way of doing things.
This takes literal milliseconds though, so it's not a very strong argument.

Shall I change the working of the feature flag (and the documentation) to the inverse of what it is now?

**Comment by tijlleenders** [comment]
@kobe-reygel 

Yes, OK if you can change the flag and the corresponding ADR we can merge this.

**Comment by kobe-reygel** [comment]
@tijlleenders implemented proposed change and documented it.

tested it with a dry run, the feature flag does what it's supposed to do

**Review by tijlleenders — APPROVED** [review]
Great!

**Pull request merged**
