### PR TITLE
Fix bug - start and deadline should be datetime not just midnight

### PR DESCRIPTION
**Pull request by egithinji**
Related to #201

### CODE REVIEW

**Comment by egithinji** [comment]
Closes #201.
Also adjusted how certain tasks that go beyond the calendar end/deadline are handled. In my opinion, its a good improvement:

**Previous**
If we had a goal `backup data every 6 hrs duration 4 after_time 15` and the calendar went from say 2022-11-19T00:00:00 to 2022-11-20T00:00:00, the scheduler would schedule two tasks, including the last one which would go past the calendar end/deadline.

**Now**
The first task will be scheduled, and the second one will be included in the `impossible` tasks. The "first_conflict_with" string will indicate, not a goalid, but the string "Passes Calendar End" (actually I'll adjust this to "Passes Deadline/Calendar End").

**Why it's better this way**
It makes no assumptions about the user's situation. For sleep, it might make sense to exceed the deadline/calendar but for some critical tasks which must complete before a deadline, the user might prefer being informed that the task cannot be scheduled, allowing them to either extend the deadline or adjust the goal.

Pinging @Tushar-4781 also because this is relevant to the front end especially the "Passes Deadline/Calendar End" string.

**Comment by tijlleenders** [comment]
Failing if it passes the deadline of the Goal I agree - but it ajoukdn't fail if it only passes the calendar end - since the world will not end ; only the schedule we want to show.

**Comment by egithinji** [comment]
I've added a test for scenario where one task goes past the deadline and reverted the other tests to allow tasks to extend past calendar end when no deadline specified.
Next will refactor as per your comment to make the tests pass.

**Review by tijlleenders — APPROVED** [review]
Great!

**Pull request merged**
