### PR TITLE
fix flamegraph

### PR DESCRIPTION
**Pull request by kobe-reygel**
fix for being able to run flamegraph again (issue: https://github.com/tijlleenders/ZinZen-scheduler/issues/301)

@tijlleenders flamegraph-rs does not work on MacOS (see documentation in PR), could you run this to verify this allows you to run the benchmarks again with "cargo flamegraph --bin flamegraph"

I picked a random test to supply to the script, I don't know which tests you had in mind to use for profiling?

### CODE REVIEW

**Comment by kobe-reygel** [comment]
in [2865563](https://github.com/tijlleenders/ZinZen-scheduler/pull/391/commits/2865563e43b80b2542d1fe37dfbda1b3d51311de) I also removed the old benchmark input and code: it was no longer in use anyway because
1) test generation already ignored the input folder
2) the benchmark code already pointed to different tests

**Comment by tijlleenders** [comment]
Yeah, this works.  
It creates a `flamegraph.svg` and a `perf.data` in the root folder: 
image

image

It would be nicer if we output it to a separate folder and .gitignore the folder.

**Comment by kobe-reygel** [comment]
@tijlleenders I changed the default test to 'demo-2-with-filler-with-budget', I think this is what you mean with 'the default goals test'?

in regards to the output folder: that is something that the user of the command 'cargo flamegraph' has to supply, we can't really define this for the end user of cargo flamegraph. I think we just need to never check in the flamegraph.svg file (I removed the currently checked in file)

**Review by tijlleenders — APPROVED** [review]
We don't have a good default goals yet so you're right, the `demo-2-with-filler-with-budget` is probably the closest thing to it.  
I'll be working on a 'complete' default goals in #386.  
The idea is to have the app startup with a whole set of pre-filled goals that corresponds to what most people would input approximately, so that you get an example that you then just have to tweak to your liking - or delete in favor of some goal-tree you build up yourself from scratch.

**Pull request merged**
